import type { Metadata } from "next";
import { Abril_Fatface, Inknut_Antiqua, Jockey_One, Josefin_Slab, Julius_Sans_One } from "next/font/google"
import "./globals.css";
import ReactThemeProvider from "./providers/theme-provider";


const joselin = Josefin_Slab({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-joselin"
})

const julius = Julius_Sans_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-julius"
})
const abril = Abril_Fatface({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-abril"
})
const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-inknut"
})
const jockey = Jockey_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-jockey"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jockey.variable} ${inknut.variable} ${jockey.variable} ${joselin.variable} ${abril.variable} ${julius.variable}`}>
        <ReactThemeProvider>
          {children}
        </ReactThemeProvider>
      </body>
    </html>
  );
}
