import { DataBarbers } from "../types/listBarbers.interface";
import imgBarber from "@public/bg-listBarber.svg";

export const dataBarbersList: DataBarbers[] = [
  {
    id: 1,
    name: "Bek Borbiev",
    experience: "2",
    status: "top barber",
    earned: 2023,
    rating: 4.9,
    service: 320,
    location: "Bishkek, Chui 12",
    image: imgBarber,
    button: "Sign up",
  },
  {
    id: 2,
    name: "Ariet",
    experience: "10",
    status: "kingsman barber",
    earned: 2002,
    rating: 5,
    service: 1000,
    location: "Bishkek, Chui 12",
    image: imgBarber,
    button: "Sign up",
  },
  {
    id: 3,
    name: "Alymbek TR",
    experience: "5",
    status: "tr barber",
    earned: 2020,
    rating: 4.8,
    service: 777,
    location: "Bishkek, Chui 12",
    image: imgBarber,
    button: "Sign up",
  },
  {
    id: 4,
    name: "Aslan Manty",
    experience: "4",
    status: "manty barber",
    earned: 2022,
    rating: 3,
    service: 480,
    location: "Bishkek, Manas 12",
    image: imgBarber,
    button: "Sign up",
  },
  {
    id: 5,
    name: "Ariet",
    experience: "10",
    status: "kingsman barber",
    earned: 2002,
    rating: 5,
    service: 1000,
    location: "Bishkek, Chui 12",
    image: imgBarber,
    button: "Sign up",
  },
  {
    id: 6,
    name: "Ariet",
    experience: "10",
    status: "kingsman barber",
    earned: 2002,
    rating: 5,
    service: 1000,
    location: "Bishkek, Chui 12",
    image: imgBarber,
    button: "Sign up",
  },
];
